package com.dietcalc.enums;

public enum FoodCategories {

    SUGARY,
    PREPAREDFOODS,
    DRINKS,
    MEATANDDERIVATIVES,
    CEREALSANDDERIVATIVES,
    FATSANDOILS,
    INDUSTRIALIZED,
    LEGUMESANDDERIVATIVES,
    MILKANDDERIVATES,
    MISCELANEOUS,
    NUTSANDSEEDS,
    EGGSANDDERIVATES,
    FISHANDSEAFOOD,
    VEGETABLESANDDERIVATIVES;

}
